name: Compilar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Descomprimir proyecto
        run: unzip ViboritaPacmanAndroid_Para_APK.zip

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Configurar Android
        uses: android-actions/setup-android@v3

      - name: Instalar Android SDK
        run: sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.7"

      - name: Compilar APK
        working-directory: ViboritaPacmanAndroid
        run: gradle assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Viborita-Pacman-APK
          path: ViboritaPacmanAndroid/app/build/outputs/apk/debug/app-debug.apk
